# finartha-v3/pyproject.toml
[project]
name = "finartha-v3"
version = "0.1.0"
description = "Finance AI Assistant with Gemini Forecast"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "streamlit",
  "pandas",
  "numpy",
  "matplotlib>=3.8",
  "yfinance>=0.2.40",
  "google-generativeai>=0.7.0",
  "python-dateutil",
  "requests",
]

[build-system]
requires = ["pdm-backend"]           # or "hatchling" if your builder supports it
build-backend = "pdm.backend"

